---
title: "Data_Import"
output: html_document
date: "2023-07-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(dplyr)
```

Read in data
```{r}
#read in files
data1 <- read_excel("~/Downloads/test1.xlsx") #, col_names = TRUE)
data2 <- read_excel("~/Downloads/test2.xlsx", col_names = TRUE)
Excel69420 <- read_excel("~/Downloads/69420Excel.xlsx", col_names = TRUE)

View(data1)

## Rename df headers
head <- data1[1,]
colnames(data1) = head
data1 <- data1[-1,]



View(data1)

df <- data1 %>%
  select(
             #overall stuff
             Subject, Group, Block, SessionDate, SessionStartDateTimeUtc,GoCorrect:InitGoRT, PercentStop,PracticeBlock:StopCorr,Trial,BkGd,GoDur,
             #distress/ upset sliders
             NegDistress.Slider1.Value,NegUpset.Slider1.Value,NeuDistress.Slider1.Value,NeuUpset.Slider1.Value, PosDistress.Slider1.Value,PosUpset.Slider1.Value, 
             #other studd?
             CorrectAnswer, EmotionalPic,Go.ACC,Go.DurationError,Go.OnsetTime,Go.RT,Go1s.ACC,
             #trauma 1 stuff
             Trauma1CogAvoi1.Slider1.Value,Trauma1Deperson1.Slider1.Value,Trauma1Derealiz.Slider1.Value,
             Trauma1Dissoc.Slider1.Value, Trauma1CogAvoi1.Slider1.Value,
             Trauma1Distress1.Slider1.Value,Trauma1EmotAvoi.Slider1.Value
             ) %>%
             mutate(Go_Stop_Trial = ifelse(BkGd == "Black", "Go",
                                    ifelse(BkGd == "Red", "Stop", NA)
                                    ))

df$`Running[Block]`
view(df)
block1 <- df %>%
  filter(`Running[Block]` == "Block1")
block2 <- df %>%
  filter(`Running[Block]` == "Block2")
block3 <- df %>%
  filter(`Running[Block]` == "Block3")
Emotion <- df %>%
  filter(`Running[Block]` == "EmotionTask")
view(block1)

```


```{r}

block1 |>
  filter(!is.na(as.double(Go.RT))) |>
  mean(Go.RT)


```


```{r}
library(tidyverse)
# install.packages("rprime")
library(rprime)
# install.packages("wrapr")
library(wrapr)
# A function to prepare all eprime data simultaneously
reduce_wm <- function(wm_path) {
  # Read in a text file generated by Eprime
  wm_lines <- read_eprime(wm_path)
  # Convert lines from an Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(wm_frames)
  # Select the columns we want for a tibble called "dat".
}

```


